name: kube-aws Action
description: Deploy and update Kubernetes clusters with kube-aws from GitHub Actions
author: Taylor D. Edmiston
inputs: 
  clusterName:
    description: Cluster name for kube-aws
    default: k8s
runs:
  using: docker
  image: Dockerfile
