name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Docker build
        # run: docker build . --file Dockerfile --tag $GITHUB_REPOSITORY:$GITHUB_SHA
        run: docker build . --file Dockerfile --tag tedmiston/kube-aws-action:latest
      - name: Docker run
        # uses: "${GITHUB_REPOSITORY}@${GITHUB_SHA}"
        uses: tedmiston/kube-aws-action@master
        with:
          clusterDirName: k8s2.example.com
        env:
          FOO_BAR: 23
          INPUT_CLUSTERDIRNAME: k8s.example.com
